### ISSUE TITLE
More PageEvent Triggers

### ISSUE THREAD

**Issue by shroominic** [pydantic/FastUI#104]
I think we need more ways to trigger PageEvents like
- OnPageLoad
- OnFormSubmit
- FromJSScript?

**Comment by samuelcolvin** [comment]
on page load should be covered by the `FireEvent` component:

https://github.com/pydantic/FastUI/blob/6b7c7cba5250eaf044bc312199fd877878334087/src/python-fastui/fastui/components/__init__.py#L240-L243

on form submit was done in #93:

https://github.com/pydantic/FastUI/blob/6b7c7cba5250eaf044bc312199fd877878334087/src/python-fastui/fastui/components/forms.py#L78

from JS should be pretty easy since page events are just CustomEvents called on the document itself:

https://github.com/pydantic/FastUI/blob/6b7c7cba5250eaf044bc312199fd877878334087/src/npm-fastui/src/events.ts#L57

I guess we could export a wrapper for this?

**Comment by shroominic** [comment]
Uhh nice thanks! Was searching in the .venv/lib but its not yet released so I will pull from git and try to implement streaming responses to fastui-chat!
