### ISSUE TITLE
**DOC ISSUE** How do i add my own components that I make in react?

### ISSUE THREAD

**Issue by ashercn97** [pydantic/FastUI#110]
I can't find the documentation for this project and I was wondering how I can make my own components for this?

**Comment by shroominic** [comment]
Not sure about fully custom components using .ts but I created my own components by subclassing already exsisting ones like here: https://github.com/shroominic/fastui-chat/blob/main/src/fastui_chat/components.py

**Comment by paddymul** [comment]
Relevant issue https://github.com/pydantic/FastUI/issues/19

**Comment by ashercn97** [comment]
I'm sorry im like new to this kinda stuff... is the file you like tagged hooked up to the demo? If so, how would I in the simplest way add my own custom component to a project im making with fastui? Sorry if this is a simple question

**Comment by hillstub** [comment]
I don't think this issue was properly resolved: I also have problems finding the proper way to add components (both on the Python side as the React side). Could you give some guidelines? (happy to submit a PR once I know what's the right thing to do).

**Comment by JulianSobott** [comment]
I hacked together a cookiecutter template, which creates a FastUI project with a custom component. I don't know if it is the right way, because I needed to adjust the `@pydantic/fastui-bootstrap` library, but it works. In the README I describe, how to add a custom component. The basic idea is to create a React project with `fastui` as dependency and some boilerplate Code. The Python App then serves the packaged files, instead of the prebuilt.
If this helps and is the right  way I could create some documentation and create a PR in this repo. 

Repo: https://github.com/JulianSobott/cookiecutter-fastui-starter

The template is very opinionated and not of the best quality, but should give an idea of how this could be done. But I am happy to answer any questions or incorporate any feedback.
