### ISSUE TITLE
Custom component lost react state when call api 

### ISSUE THREAD

**Issue by dangex** [pydantic/FastUI#162]
I am working with custom components and native components fastui, when API calls to render components that already exist, all components render again that´s not problem but I can note that customs components lost their state. I'm not reloading the page.  why lost state ? I note that custom componentes mount and unmount several times every call api but other´s components like Table mount once and its state persists

**Comment by samuelcolvin** [comment]
I don't really understand the question, as you say other components don't loose their state, so I don't think custom components will.

**Comment by zzachattack2** [comment]
I ran into something similar with custom components and found that it was due to how customRender requires returning a callback to create the component. In the custom component example, that callback reference is recreated in every call to customRender, causing the component to be remounted on each render. 

I was able to get around this by memoizing the callback in customRender. I'm no expert at react, so I don't doubt there might be a better way. 

```typescript
const customRender: CustomRender = (props) => {
  const { type } = props
  if (type === 'Custom' && props.subType === 'MonacoEditor') {
    //return () => <MonacoEditor {...props} />
    return useCallback(() => <MonacoEditor {...props} />, [])
  } else {
    return bootstrap.customRender(props)
  }
}
```
