### ISSUE TITLE
Proposal: what about using third-party libraries to create forms based on JSON Schema?

### ISSUE THREAD

**Issue by hasansezertasan** [pydantic/FastUI#199]
Hey there 👋!

I used [json-editor](https://github.com/json-editor/json-editor) to create forms from Pydantic Models (through JSON Schema) in some FastAPI applications I developed. Still, there are more powerful and modern options to achieve this using ReactJS (which I don't use at all).

[rjsf-team/react-jsonschema-form:](https://github.com/rjsf-team/react-jsonschema-form) is a "A React component for building Web forms from JSON Schema." and I believe it can be used within FastUI Client (JS Library). 🚀.

> There are (too) many other options to be considered but as far as I can see, it's the most popular choice in the React ecosystem.

What do you think about it?

Thanks for reading 😇, have a nice day 🌔.

**Comment by samuelcolvin** [comment]
Thanks for asking.

If you're using another library, why use FastUI? FastUI and work in a FastAPI app alongside other views.

Similarly, if you're using FastUI, why do you need another library?

Generally, I'm happy to consider a specific request, but personally I'm happy with how FastUI builds forms, and extending that when I need to.

**Comment by samuelcolvin** [comment]
rjsf-team/react-jsonschema-form couldn't be used with FastUI without moving all our form logic to the client side, and submitting forms via some custom solution that doesn't leverage multiparty form submission - e.g. JSON.

I think that's a mistake, mostly because upload of large files will get very inefficient, and also make a future frontend for FastUI based on server side templates, html and htmx much harder.
