### ISSUE TITLE
Issue with toast

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/FastUI#282]
See demo for details, need to resolve before v0.6.0: https://fastui-demo.onrender.com/components#toast

**Comment by sydney-runkle** [comment]
@ManiMozaffar,

I'm hoping to finish up the docs by the end of the week, then crank through some PRs and issues next week :).

**Comment by ManiMozaffar** [comment]
Understood. Will do it over the weekend then! At Noah labs, we're using FastUI to write internal tool and it's been game changer for us, because development speed is just way faster.

Would be very nice if documentation comes with the limitation for the component. I haven't looked through the toast component yet, but that would awesome to have toast rendered from "form submission response".

**Comment by sydney-runkle** [comment]
I believe @hramezani figured out that we just need to build the internal packages for this to work - should be resolved tomorrow!
