### ISSUE TITLE
how do I set an initial value for form field with search_url json_schema_extra

### ISSUE THREAD

**Issue by fmrib00** [pydantic/FastUI#340]
My form has a str field with search_url:
class OrderSubmit(BaseModel):
    order_id:           str
    region:             str = Field(json_schema_extra={'search_url': '/api/region_search', 'placeholder': 'Select Region...'})
    ...

The search filter is coded exactly like the country filter example in the demo's city table, which returns a SelectSearchResponse.

firstly, I tried to set initial values for the form as the following:
            c.Page(
                components=[
                    c.Heading(text='Add Order', level=2),
                    c.ModelForm(model=OrderSubmit submit_url='/api/order-upload/add', initial={'order_id': order_id, 'region': 'All'})
                ]
            )

It worked only for the order_id part, region showed up empty, which I thought must be because it needed to be in the form required by the search function. I then changed the initial value for region with label and value info like:
                                initial={'order_id': order_id, 
                                            'region': {'label':'All', 'options': [{'value':'All', 'label':'All'}]}

After that, the interface looked right with "All" showed up correctly in region field, but I can't submit the form as the field was treated as having no input and it is a required field.

So what is the correct way to set an initial value for fields with search_url? Thanks!

**Comment by schatimo** [comment]
Please try to format your example in the future in markdown style such that it is more readable.

The type of your model `OrderSubmit` for the field `region` mismatches with the type of the `initial` argument for the key `region`. Thus, in `initial` the key `region` is a `list[str]`, while in `OrderSubmit` it is a `str`. When you align those two types, it will work. I cannot help you further with your example as the snippets you provided are not reproducible but it should work with the described alignment of types.

For instance considering changing https://github.com/pydantic/FastUI/blob/e8b12f5975d168d5904e22b64c26cdd707c04817/demo/forms.py#L94 to
```python
c.ModelForm(model=SelectForm, display_mode='page', submit_url='/api/forms/select', initial={"search_select_single": SelectOption(value="Norway", label="Norway"), "search_select_multiple": [SelectOption(value="Norway", label="Norway")]}),
```
in order to have initial values for the fields `search_select_single` and `search_select_multiple`.

**Comment by fmrib00** [comment]
thank you so much for your help! The correct way, as you pointed out, is to use the SelectOption class, which solves my problem!

**Comment by fmrib00** [comment]
problem solved!
